<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd5c881d925536bcb1bbf66f3c6b22b70
{
    public static $prefixesPsr0 = array (
        'I' => 
        array (
            'ImageCache' => 
            array (
                0 => __DIR__ . '/..' . '/nielse63/phpimagecache/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInitd5c881d925536bcb1bbf66f3c6b22b70::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
